### ISSUE TITLE
Issue while building 

### ISSUE THREAD

**Issue by sarveshraj** [cibuilds/hugo#161]
Hi,

This is my first time using circleCI so forgive me if this question sounds novice.
I am getting a build error when using your docker image (screenshot attached)
<img width="1159" alt="Screenshot 2020-04-14 at 10 32 02 PM" src="https://user-images.githubusercontent.com/35839390/79253208-70c44700-7ea0-11ea-8d37-6adc3849c353.png">

This is my circle ci config file: https://github.com/sarveshraj/me/blob/circleci-project-setup/.circleci/config.yml

**Comment by felicianotech** [comment]
Hi,

No worries, I'm here to help.

If you are using a recent version of the Hugo image, `apk` is not available because that's only in Alpine-based images. This Hugo image is Ubuntu-based.

I see two options here:

1. Use the package manager in Ubuntu, `apt` to install Node.js and npm
2. Or you can use the [CircleCI Node.js orb](https://circleci.com/orbs/registry/orb/circleci/node) to install Node.js and npm.

**Comment by sarveshraj** [comment]
Thanks for the quick reply. I am using version 0.69 of the Hugo image. A couple of follow-up questions.
1. Could you tell me what part of my config file is triggering the `apk add --update nodejs npm` command? 
2. As I understand I will be using the suggested CircleCI orb in addition to your docker image as a precursor. Am I correct?

**Comment by felicianotech** [comment]
I don't know, it looks like you removed it now.

Yes, you can use my image for Hugo and the Node.js orb for dynamically installing Node.js into your build.
