### ISSUE TITLE
Using on circleci multi-docker setup

### ISSUE THREAD

**Issue by am** [cibuilds/hugo#89]
I'm trying to figure out how to use this image alongside with node. 

> Currently, this Docker image is designed to be used as a base image on CircleCI 2.0 for building, testing, and deploying Hugo based websites.

Does this mean that it won't work on multi-image configuration job?

My current circleci configuration is the [following](https://github.com/am/www.bit-ink.com/blob/circleci/.circleci/config.yml#L9).

**Comment by felicianotech** [comment]
Taking another look at how the Docker executor on CircleCI would be useful here. The first image that you list in the config, that's your primary container. All commands you run will be run from that containers. Any other image you list are secondary images and you can interact with their services via TCP/IP.

You'd need to have Hugo and Node in the same primary image in order to use them together.
